version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aspporcelette-db
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - aspporcelette-network


  backend:
    build:
      context: ./aspPorcelette
      dockerfile: Dockerfile
    container_name: aspporcelette-backend
  
    ports:
      - "5070:8080"
    environment:
      # Ligne 1 : ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_ENVIRONMENT=Production
      # Ligne 2 : Correction de l'URL (suppression de l'espace 'http: //')
      - ASPNETCORE_URLS=http://+:8080
      # Ligne 3 : Encapsulation de la chaîne de connexion dans des guillemets simples pour éviter les erreurs de parsing YAML
      - 'ConnectionStrings__DefaultConnection=Server=db,1433;Database=5070;User Id=sa;Password=YourStrong!Passw0rd123;TrustServerCertificate=True;MultipleActiveResultSets=true'
    networks:
      - aspporcelette-network
    restart: unless-stopped

  frontend:
    build:
      context: ./asp-porcelette-front
      dockerfile: Dockerfile
    container_name: aspporcelette-frontend
    # Le frontend est exposé sur le port 8080 de l'hôte (votre machine)
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - aspporcelette-network
    restart: unless-stopped

volumes:
  sqldata:

networks:
  aspporcelette-network:
    driver: bridge